// automatically generated by admSerialization.py do not edit
#include "string"
#pragma once
typedef struct {
uint32_t preset;
uint32_t profile;
uint32_t rc_mode;
uint32_t quality;
uint32_t bitrate;
uint32_t max_bitrate;
uint32_t gopsize;
uint32_t lookahead;
}ffqsvav1_encoder;
