// automatically generated by admSerialization.py, do not edit!
extern const ADM_paramList ffqsvav1_encoder_param[]={
 {"preset",offsetof(ffqsvav1_encoder,preset),"uint32_t",ADM_param_uint32_t},
 {"profile",offsetof(ffqsvav1_encoder,profile),"uint32_t",ADM_param_uint32_t},
 {"rc_mode",offsetof(ffqsvav1_encoder,rc_mode),"uint32_t",ADM_param_uint32_t},
 {"quality",offsetof(ffqsvav1_encoder,quality),"uint32_t",ADM_param_uint32_t},
 {"bitrate",offsetof(ffqsvav1_encoder,bitrate),"uint32_t",ADM_param_uint32_t},
 {"max_bitrate",offsetof(ffqsvav1_encoder,max_bitrate),"uint32_t",ADM_param_uint32_t},
 {"gopsize",offsetof(ffqsvav1_encoder,gopsize),"uint32_t",ADM_param_uint32_t},
 {"lookahead",offsetof(ffqsvav1_encoder,lookahead),"uint32_t",ADM_param_uint32_t},
 {"gpu_index",offsetof(ffqsvav1_encoder,gpu_index),"uint32_t",ADM_param_uint32_t},
{NULL,0,NULL}
};
